ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "arg_ros_tools"
  site-url: "https://ARG-NCTU.github.io/arg_ros_tools/"
  description: "A toolset for navigation(ex:rosbag) created by arg lab"
  twitter-card: true
  open-graph: true
  reader-mode: true
  repo-branch: master
  repo-url: "https://github.com/ARG-NCTU/arg_ros_tools/tree/master/"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/ARG-NCTU/arg_ros_tools/tree/master/"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
